"""Command-line parsing for SafeLLM4SE comparison reports."""

import argparse
from pathlib import Path

from safellm4se.sampling.config.logger import LOG_LEVELS

from safellm4se.reporting.cli import MandatoryAwareDefaultsHelpFormatter
from safellm4se.comparing.models import ComparisonSettings


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser used by comparing.py.

    Returns:
        A configured argument parser for two-sample comparison reports.
    """
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="SafeLLM4SE two-sample CSV comparison reporting.",
        formatter_class=MandatoryAwareDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--h",
        action="help",
        help="Show this help message and exit.",
    )
    parser.add_argument(
        "--input",
        required=True,
        metavar="FILE_NAME",
        help="Input CSV file generated by sample.py.",
    )
    parser.add_argument(
        "--output",
        default="comparing.csv",
        metavar="FILE_NAME",
        help="Output CSV comparison report file.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show INFO and higher log messages on screen.",
    )
    parser.add_argument(
        "--log",
        dest="log_level",
        choices=LOG_LEVELS,
        type=str.upper,
        metavar="LEVEL",
        default=None,
        help=(
            "Show log messages on screen from the selected level. Accepted "
            f"values: {', '.join(LOG_LEVELS)}."
        ),
    )
    parser.add_argument(
        "--task-id-1",
        required=True,
        metavar="TASK_ID",
        help="First task identifier to include in the comparison report.",
    )
    parser.add_argument(
        "--task-name-1",
        metavar="NAME",
        default=None,
        help="Optional first task name to display in generated plots.",
    )
    parser.add_argument(
        "--task-id-2",
        required=True,
        metavar="TASK_ID",
        help="Second task identifier to include in the comparison report.",
    )
    parser.add_argument(
        "--task-name-2",
        metavar="NAME",
        default=None,
        help="Optional second task name to display in generated plots.",
    )
    parser.add_argument(
        "--test-type",
        required=True,
        choices=["paired", "independent"],
        help="Experimental design used to comparing both distributions.",
    )
    parser.add_argument(
        "--confidence-level",
        default=0.95,
        type=float,
        metavar="CONFIDENCE_LEVEL",
        help="Confidence level used for confidence intervals.",
    )
    parser.add_argument(
        "--boxplot",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a two-sample boxplot.",
    )
    parser.add_argument(
        "--violin",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a two-sample violin plot.",
    )
    parser.add_argument(
        "--ECDF",
        "--ecdf",
        dest="ecdf",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a two-sample ECDF plot.",
    )
    parser.add_argument(
        "--raincloud",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a two-sample raincloud plot.",
    )
    parser.add_argument(
        "--KDE",
        "--kde",
        dest="kde",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a two-sample KDE plot.",
    )
    return parser


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for a comparison report generation run.

    Returns:
        The parsed command-line namespace.
    """
    return build_parser().parse_args()


def settings_from_args(args: argparse.Namespace) -> ComparisonSettings:
    """Create comparison settings from parsed command-line arguments.

    Args:
        args: Parsed command-line arguments.

    Returns:
        Runtime settings for comparison report generation.
    """
    return ComparisonSettings(
        input_path=Path(args.input),
        output_path=Path(args.output),
        boxplot_path=_optional_path(args.boxplot),
        violin_path=_optional_path(args.violin),
        ecdf_path=_optional_path(args.ecdf),
        raincloud_path=_optional_path(args.raincloud),
        kde_path=_optional_path(args.kde),
        task_id_1=args.task_id_1,
        task_id_2=args.task_id_2,
        task_name_1=args.task_name_1,
        task_name_2=args.task_name_2,
        test_type=args.test_type,
        confidence_level=args.confidence_level,
    )


def _optional_path(file_name: str | None) -> Path | None:
    """Return a Path for an optional file name.

    Args:
        file_name: Optional command-line file name.

    Returns:
        A path when a file name was provided; otherwise, None.
    """
    if file_name is None:
        return None
    return Path(file_name)
