"""Command-line parsing for SafeLLM4SE sampling reports."""

import argparse
from pathlib import Path

from safellm4se.sampling.config.logger import LOG_LEVELS

from safellm4se.reporting.models import ReportingSettings


class MandatoryAwareDefaultsHelpFormatter(argparse.ArgumentDefaultsHelpFormatter):
    """Formatter that shows mandatory arguments without reporting a None default."""

    def _get_help_string(self, action: argparse.Action) -> str:
        """Return the help text with mandatory status shown for required arguments.

        Args:
            action: Parser action whose help text is being formatted.

        Returns:
            The formatted help text for the action.
        """
        help_text: str = action.help or ""
        if action.required:
            return f"{help_text} (mandatory)"
        return super()._get_help_string(action)


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser used by report.py.

    Returns:
        A configured argument parser for report generation.
    """
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="SafeLLM4SE sampling CSV reporting.",
        formatter_class=MandatoryAwareDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--h",
        action="help",
        help="Show this help message and exit.",
    )
    parser.add_argument(
        "--input",
        required=True,
        metavar="FILE_NAME",
        help="Input CSV file generated by sample.py.",
    )
    parser.add_argument(
        "--output",
        default="report.csv",
        metavar="FILE_NAME",
        help="Output CSV report file.",
    )
    parser.add_argument(
        "--boxplot",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a boxplot of theta observations.",
    )
    parser.add_argument(
        "--violin",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a violin plot of theta observations.",
    )
    parser.add_argument(
        "--ECDF", "--ecdf",
        dest="ecdf",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for an ECDF plot of theta observations.",
    )
    parser.add_argument(
        "--raincloud",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a raincloud plot of theta observations.",
    )
    parser.add_argument(
        "--KDE", "--kde",
        dest="kde",
        metavar="FILE_NAME",
        default=None,
        help="Optional SVG output file for a KDE plot of theta observations.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show INFO and higher log messages on screen.",
    )
    parser.add_argument(
        "--log",
        dest="log_level",
        choices=LOG_LEVELS,
        type=str.upper,
        metavar="LEVEL",
        default=None,
        help=(
            "Show log messages on screen from the selected level. Accepted "
            f"values: {', '.join(LOG_LEVELS)}."
        ),
    )
    parser.add_argument(
        "--task-id",
        required=True,
        metavar="TASK_ID",
        help="Task identifier to include in the report.",
    )
    parser.add_argument(
        "--task-name",
        metavar="NAME",
        default=None,
        help="Optional task name to display in generated plots.",
    )
    parser.add_argument(
        "--confidence-level",
        default=0.95,
        type=float,
        metavar="CONFIDENCE_LEVEL",
        help="Confidence level used for confidence intervals.",
    )
    parser.add_argument(
        "--ci-method",
        choices=["auto", "t", "bootstrap"],
        default="auto",
        help=(
            "Confidence interval method for continuous metrics; binary metrics "
            "always use Wilson."
        ),
    )
    return parser


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for a report generation run.

    Returns:
        The parsed command-line namespace.
    """
    return build_parser().parse_args()


def settings_from_args(args: argparse.Namespace) -> ReportingSettings:
    """Create reporting settings from parsed command-line arguments.

    Args:
        args: Parsed command-line arguments.

    Returns:
        Runtime settings for report generation.
    """
    return ReportingSettings(
        input_path=Path(args.input),
        output_path=Path(args.output),
        boxplot_path=_optional_path(args.boxplot),
        violin_path=_optional_path(args.violin),
        ecdf_path=_optional_path(args.ecdf),
        raincloud_path=_optional_path(args.raincloud),
        kde_path=_optional_path(args.kde),
        task_id=args.task_id,
        task_name=args.task_name,
        confidence_level=args.confidence_level,
        ci_method=args.ci_method,
    )


def _optional_path(file_name: str | None) -> Path | None:
    """Return a Path for an optional file name.

    Args:
        file_name: Optional command-line file name.

    Returns:
        A path when a file name was provided; otherwise, None.
    """
    if file_name is None:
        return None
    return Path(file_name)
